In [28]:
## 1) Write a program to create a 5 dimensional array with all zeros and ones
import numpy as np
y=np.array([0],ndmin=5)
x=np.array([1],ndmin=5)
print(x)
print(y)

[[[[[1]]]]]
[[[[[0]]]]]


In [24]:
## 2) Write a program to create an array of 10 zeros,10 ones, and 10 fives in row 1 2 and 3 which create a new array of shape (3,10)
array1=np.zeros(10,)
array2=np.ones(10,)
array=np.ones(10)*5
print(array1)
print(array2)
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [40]:
## 3) Write a program to create a 3x4 matrix filled with values from 10 to 21.
m=np.arange(10,22).reshape(3,4)
print(m)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [42]:
## 4) Write a  program to create a 10x10 zero matrix with elements on the main diagonal equal to 0,1,2,3,4,5,6,7,8,9,
np.diag([0,1,2,3,4,5,6,7,8,9])

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 9]])

In [72]:
## 5)Write a program to create a 4x4 array. Create an array from below array by swapping first and last, second and third columns.
import numpy as np
array=np.arange(1,17).reshape(4,4)
print(array)
array[:,::-1]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9],
       [16, 15, 14, 13]])

In [52]:
## 6) Write a program to reverse an array (the first element becomes the last).
# Given array: [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 ]
array= [12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27]
array[::-1]

[27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12]

In [71]:
## 7) Write a program to access all the elements greater than 30 and less than 80 and multiples of 5 from an array of shape 10,10 .Elements range from 1 to 100
import numpy as np
x=np.random.randint(1,101,(10,10))
new_array=x[(x>30)&(x<80)&(x%5==0)]
print(new_array)

[70 55 60 35 40 60 35 45 35 45 55]


In [81]:
## 8) Write a program to create a 2D array with 1 on the border and 0 inside.
import numpy as np
x=np.ones((5,5))
x[1:-1,1:-1]=0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [82]:
# 9) Write a program to create a checkerboard pattern .Don't use default array function Checkerboard pattern:
import numpy as np
def printcheckerboard(n):
    print("Checkerboard pattern:")
    x = np.zeros((n, n), dtype=int)
    x[1::2, ::2] = 1
    x[::2, 1::2] = 1
    for i in range(n):
        for j in range(n):
            print(x[i][j], end=" ")
        print()
n = 8
printcheckerboard(n)

Checkerboard pattern:
0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 
0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 
0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 
0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 


In [83]:
# 10) Write a program to find common values between two arrays.
array1= [10,20,40,60]
array2= [10,30,40,50]
np.intersect1d(array1,array2)

array([10, 40])

In [104]:
# 11) Write a program to create an array 2d array and then reshape into 1d array
x2=np.array([[10,20,10],[1,23,4]])

In [106]:
x2.flatten()

array([10, 20, 10,  1, 23,  4])

In [112]:
## 12) Write a user defined function for creating a 1 or 2d array from scratch without using array functions

def create_array(rows, cols=None, initial_value=None):
    if cols is None:
        if initial_value is None:
            return [0] * rows
        else:
            return [initial_value] * rows
    else:
        if initial_value is None:
            return [[0] * cols for _ in range(rows)]
        else:
            return [[initial_value] * cols for _ in range(rows)]
one_dimensional_array = create_array(5, initial_value=0)
print(one_dimensional_array)
two_dimensional_array = create_array(3, 4, initial_value='2')
for row in two_dimensional_array:
    print(row)





[0, 0, 0, 0, 0]
['2', '2', '2', '2']
['2', '2', '2', '2']
['2', '2', '2', '2']
